name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        run: |
          docker build -t custom_redmine:latest .

      - name: Run Redmine container
        run: |
          docker run -d --name redmine_test -p 3000:3000 custom_redmine:latest

      - name: Wait for Redmine to be ready
        run: |
          for i in {1..30}; do
            if curl -fs http://localhost:3000/ > /dev/null; then
              echo "Redmine is ready"
              break
            else
              echo "Waiting for Redmine to be ready..."
              sleep 10
            fi
          done

      - name: Fetch API Key and URL
        run: |
          echo "Fetching API Key and URL from logs..."
          KEY=$(docker logs redmine_test 2>&1 | grep "Admin API Key:" | awk -F': ' '{print $2}')
          if [ -z "$KEY" ]; then
            echo "Failed to retrieve Admin API Key"
            exit 1
          fi
          echo "Admin API Key: $KEY"
          echo "REDMINE_API_KEY=$KEY" >> $GITHUB_ENV
          echo "REDMINE_URL=http://localhost:3000" >> $GITHUB_ENV

      - name: Run tests
        env:
          REDMINE_API_KEY: ${{ env.REDMINE_API_KEY }}
          REDMINE_URL: ${{ env.REDMINE_URL }}
        run: |
          echo "Running tests with API Key: $REDMINE_API_KEY"
          bundle exec rspec
