name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    services:
      redmine_test:
        build:
          context: .
          dockerfile: Dockerfile
        image: custom_redmine:latest
        ports:
          - '3000:3000'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'

      - name: Install dependencies
        run: |
          bundle install --jobs 4 --retry 3

      - name: Fetch API Key and URL
        run: |
          echo "Fetching API Key and URL from logs..."
          KEY=$(docker logs redmine_test 2>&1 | grep "Test User API Key:" | awk -F': ' '{print $2}')
          if [ -z "$KEY" ]; then
            echo "Failed to retrieve Admin API Key"
            exit 1
          fi
          echo "Test User API Key: $KEY"
          echo "REDMINE_API_KEY=$KEY" >> $GITHUB_ENV
          echo "REDMINE_URL=http://localhost:3000" >> $GITHUB_ENV

      - name: Run tests
        env:
          REDMINE_API_KEY: ${{ env.REDMINE_API_KEY }}
          REDMINE_URL: ${{ env.REDMINE_URL }}
        run: |
          echo "Running tests with API Key: $REDMINE_API_KEY"
          bundle exec rspec
