name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Ruby environment
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          bundle install --jobs 4 --retry 3

      # Шаг 4: Build Redmine
      - name: Build Redmine image
        run: |
          docker build -t redmine_test:latest .

      # Шаг 5: Run Redmine
      - name: Run Redmine container
        run: |
          docker run -d --name redmine_test -p 3000:3000 redmine_test:latest

      # Шаг 6: Wait for Redmine ready
      - name: Wait for Redmine to be healthy
        run: |
          for i in {1..30}; do
            if curl -fs http://localhost:3000/ > /dev/null; then
              echo "Redmine is healthy"
              break
            else
              echo "Waiting for Redmine to be healthy..."
              sleep 10
            fi
          done

      # Шаг 7: Fetch variables
      - name: Get Admin API key
        run: |
          KEY=$(docker exec redmine_test rails runner "puts User.find_by(login: 'admin').api_key")
          echo "REDMINE_API_KEY=$KEY" >> $GITHUB_ENV
          echo "REDMINE_URL=http://localhost:3000" >> $GITHUB_ENV

      # Шаг 8: Run tests
      - name: Run tests
        env:
          REDMINE_API_KEY: ${{ env.REDMINE_API_KEY }}
          REDMINE_URL: ${{ env.REDMINE_URL }}
        run: bundle exec rspec